apiVersion: v1
kind: Service
metadata:
  name: name-vault-js-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: name-vault-js
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.app.nodePort }}